services:
  api:
    build: .
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      PORT: 3001
      JWT_SECRET: "dev_secret_change_me_please_12345"
      JWT_EXPIRES_IN: "1h"
      DB_TYPE: sqlite
      DB_PATH: "/app/data/database.sqlite"
      DB_SYNCHRONIZE: "true"
    volumes:
      - ./data:/app/data
